name: employee_directory_application
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.3
  pretty_dio_logger: ^1.1.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  cached_network_image: ^3.2.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.4
  lint: ^1.10.0

flutter:
  uses-material-design: true
